### PR TITLE
fix(item): Check for array size in Cloud Staff

### LINKED ISSUE #1011: Bug: Cloud Staff Crashing
### What Feature Types Apply to This Bug?

Item

### Other Type

_No response_

### What Type of Bug Is This?

Crash

### Forge Version

44.1.0

### The Aether Version

1.19.3 0.3.1

### Is This Bug a Conflict With Another Mod?

_No response_

### Client Log

_No response_

### Crash Report (if applicable)

https://gist.github.com/AtomicJuno/15ddc0add9c55e66455c0c9a53ecefcd

### Steps to Reproduce

Unknown method of reproducing; Please check the crash log

### What You Expect To Happen

Game plays as normal with cloud staff

### What Actually Happened

Game Crashed after a while; log mentions cloud staff

### Additional Details

_No response_

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by bconlon1**
closes #1011

### CODE REVIEW

File: src/main/java/com/gildedgames/aether/item/combat/loot/CloudStaffItem.java [hunk 1]
```diff
@@ -74,7 +74,7 @@ public InteractionResultHolder<ItemStack> use(Level level, Player player, Intera
     public boolean onEntitySwing(ItemStack stack, LivingEntity entity) {
         if (entity instanceof Player player) {
             AetherPlayer.get(player).ifPresent(aetherPlayer -> {
-                if (!aetherPlayer.getCloudMinions().isEmpty()) {
+                if (!aetherPlayer.getCloudMinions().isEmpty() && aetherPlayer.getCloudMinions().size() == 2) {
```
Comment (Burning-Cactus) [inline src/main/java/com/gildedgames/aether/item/combat/loot/CloudStaffItem.java]: Instead of hardcoding this to a size of 2, use a for loop if it's off cooldown. Also, aetherPlayer.getPlayer() is redundant when you have a local variable for player.

**Review by Burning-Cactus — CHANGES_REQUESTED** [review]

**Review by Burning-Cactus — APPROVED** [review]
lgtm
