### PR TITLE
Fixed valkyrie queen messages.

### LINKED ISSUE #695: Bug: Valkyrie Queen text and dialog
### What Feature Types Apply to This Bug?

Entity

### Other Type

_No response_

### What Type of Bug Is This?

_No response_

### Forge Version

41.0.62

### The Aether 1 Version

1.0.0

### Is This Bug a Conflict With Another Mod?

_No response_

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

1. Create a world with the latest 1.19 Aether 1 build. 
2. Spawn the Valkyrie Queen.
3. Click on it.
4. Select "I wish to fight you!", WITHOUT medals.
5. Click on "I'll return when I have them (0/10)"
6. Look the Valkyrie Queen's response, it's wrong.

and 

1. Create a world with the latest 1.19 Aether 1 build. 
2. Spawn the Valkyrie Queen.
3. Click on it.
4. Select "I wish to fight you!" WITH medals.
5. Attack it IN CREATIVE MODE.
6. Look, every time you hit her, she says "This will be your final battle!", this is not normal.

### What You Expect To Happen

Normally, when you click on "I'll come back when I have them (0/10)", it should say "Take your time.", instead of the following sentence: "Very well then. Bring me ten medals from my subordinates to prove your worth, then we'll see".

and

Normally, when you first hit the Valkyrie Queen in a fight, it says "This will be your final battle!", but it's not supposed to show up every time you hit her, in creative mode, like the survival mode.

### What Actually Happened

When you attack the Valkyrie Queen in creative mode, with each damage, she displays the text "This will be your final battle!" Also, when you click on her dialogue that says "I wish to fight you!", when you click on "I'll return when I have them (0/10)" she says "Very well then. Bring me ten medals from my subordinates to prove your worth, then we'll see", instead of saying "Take your time". 

### Additional Details

_No response_

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by Burning-Cactus**
Closes #695

### CODE REVIEW

File: src/main/java/com/gildedgames/aether/entity/monster/dungeon/ValkyrieQueen.java [hunk 1]
```diff
@@ -113,6 +113,9 @@ public void readAdditionalSaveData(@Nonnull CompoundTag tag) {
     public void customServerAiStep() {
         super.customServerAiStep();
         this.bossFight.setProgress(this.getHealth() / this.getMaxHealth());
+        if (this.getTarget() == null) {
+            this.bossFight.setVisible(false);
```
Comment (bconlon1) [inline src/main/java/com/gildedgames/aether/entity/monster/dungeon/ValkyrieQueen.java]: Personally I think the boss fight should still be visible in creative, similarly the isCreative() check lower down I don't think is necessary; the only thing this really needs in my opinion is that switch out for checking !this.bossFight.isVisible() to know when to display the fight begin message.

**Review by bconlon1 — APPROVED** [review]
lgtm
