### PR TITLE
improv: dungeon fixes

### LINKED ISSUE #1979: Bug: Dungeon blocks and entities don't function correctly
Deliberately vague issue report, details on the dev server

### PR DESCRIPTION
**Pull request by bconlon1**
#1979

### CODE REVIEW

File: src/main/java/com/aetherteam/aether/AetherTags.java [hunk 1]
```diff
@@ -174,6 +174,7 @@ public static class Entities {
 		public static final TagKey<EntityType<?>> UNHOOKABLE = tag("unhookable");
 		public static final TagKey<EntityType<?>> TREATED_AS_AETHER_ENTITY = tag("treated_as_aether_entity");
 		public static final TagKey<EntityType<?>> TREATED_AS_VANILLA_ENTITY = tag("treated_as_vanilla_entity");
+		public static final TagKey<EntityType<?>> DUNGEON_ENTITIES = tag("treated_as_vanilla_entity");
```
Comment (Drullkus) [inline src/main/java/com/aetherteam/aether/AetherTags.java]: Filename copied from line above, should be renamed

**Review by Drullkus — CHANGES_REQUESTED** [review]
One small issue to fix with the tag

**Review by Drullkus — APPROVED** [review]
LGTM!
