### PR TITLE
fix: Aerclouds no longer act as ground during flight

### LINKED ISSUE #1380: Bug: Blue Aercloud canceling elytra flight
### What Feature Types Apply to This Bug?

Block

### Other Type

_No response_

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.58

### The Aether Version

1.19.4-1.0.0-beta.3-forge

### Is This Bug a Conflict With Another Mod?

No

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

Step 1) Deploy elytra
Step 2) Fly into blue aercloud

### What You Expect To Happen

Blue Aercloud effect to launch me up, and allow me to use the speed boost to extend flight range

### What Actually Happened

Elytra flight is cancelled, requiring me to redeploy the elytra and thus losing momentum

### Additional Details

_No response_

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

### PR DESCRIPTION
**Pull request by bconlon1**
closes #1380

### CODE REVIEW

**Review by Jonathing — APPROVED** [review]

File: src/main/java/com/aetherteam/aether/block/natural/AercloudBlock.java [hunk 1]
```diff
@@ -44,7 +45,9 @@ public void entityInside(BlockState state, Level level, BlockPos pos, Entity ent
 		if (entity.getDeltaMovement().y < 0.0) {
 			entity.setDeltaMovement(entity.getDeltaMovement().multiply(1.0, 0.005, 1.0));
 		}
-		entity.setOnGround(true);
+		if (!(entity instanceof Player player) || !player.getAbilities().flying) {
+			entity.setOnGround(true);
+		}
```
Comment (Jonathing) [inline src/main/java/com/aetherteam/aether/block/natural/AercloudBlock.java:50]: Actually, this does pose a slight problem: players who reach the bottom of the aercloud block while flying with an elytra will continue to "fly" in it, even though the block itself is not solid. Might it be better to only include this change in the blue aercloud?

**Review by OzPayn — APPROVED** [review]
works how I'd expect, gj
