### PR TITLE
Fix: The world tick listener now checks against the minimum build height.

### LINKED ISSUE #394: Improve height check determining if a player has fallen out of the aether
Currently it checks against `0` instead of `world.getMinBuildHeight()`. This isn't a problem because we haven't deviated our world heights but this will be if a datapacker does

image

I also recommend not counting the player as falling if either: Player's `Abilities.flying == true` or `player.isSpectator()`

### PR DESCRIPTION
**Pull request by Burning-Cactus**
Players now fall out of the Aether at the dimension type's minimum build height instead of y=0. Players flying through creative or spectator can't fall out of the Aether.
Closes #394

### CODE REVIEW

File: src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java [hunk 1]
```diff
@@ -145,7 +145,10 @@ public static void onWorldTick(TickEvent.WorldTickEvent event) {
                 if (event.phase == TickEvent.Phase.END) {
                     if (!AetherConfig.COMMON.disable_falling_to_overworld.get()) {
                         for (Entity entity : world.getEntities(EntityTypeTest.forClass(Entity.class), Objects::nonNull)) {
-                            if (entity.getY() <= 0 && !entity.isPassenger()) {
+                            if (entity.getY() <= world.getMinBuildHeight() && !entity.isPassenger()) {
+                                if(entity instanceof Player player && (player.getAbilities().flying)) {
```
Comment (Drullkus) [inline src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java]: Please also check if the player is Spectator

**Review by Drullkus — CHANGES_REQUESTED** [review]

File: src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java (hunk 1 above)
Comment (Drullkus) [reply src/main/java/com/gildedgames/aether/common/event/listeners/DimensionListener.java]: Spectator is also considered flying, resolved

**Review by Drullkus — APPROVED** [review]

**Review by Drullkus — APPROVED** [review]
Looks good to me!

**Review by bconlon1 — APPROVED** [review]
lgtm
