### PR TITLE
fix: Tag for crafting skyroot buckets

### LINKED ISSUE #1313: Bug: Skyroot Buckets not included in Skyroot tool crafting tag
### What Feature Types Apply to This Bug?

_No response_

### Other Type

Tags/Addon-useable content

### What Type of Bug Is This?

Compatibility

### Forge Version

/

### The Aether Version

beta.2

### Is This Bug a Conflict With Another Mod?

_No response_

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

Just try crafting Skyroot Buckets with any item with the SKYROOT_TOOL_CRAFTING tag that is not Skyroot Planks themeselves.

### What You Expect To Happen

I expected the Skyroot Bucket to be craftable and included in tag.

### What Actually Happened

Obvious.

### Additional Details

_No response_

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

### PR DESCRIPTION
**Pull request by bconlon1**
closes #1313

### CODE REVIEW

File: src/main/java/com/aetherteam/aether/data/resources/builders/AetherBiomeBuilders.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public static Biome makeDefaultBiome(BiomeGenerationSettings.Builder builder) {
                         .addMobCharge(AetherEntityTypes.AERWHALE.get(), 0.5, 0.11)
 
                         .addSpawn(AetherMobCategory.AETHER_DARKNESS_MONSTER, new MobSpawnSettings.SpawnerData(AetherEntityTypes.COCKATRICE.get(), 8, 1, 1))
-                        .addSpawn(AetherMobCategory.AETHER_SKY_MONSTER, new MobSpawnSettings.SpawnerData(AetherEntityTypes.ZEPHYR.get(), 15, 1, 1))
+                        .addSpawn(AetherMobCategory.AETHER_SKY_MONSTER, new MobSpawnSettings.SpawnerData(AetherEntityTypes.ZEPHYR.get(), 20, 1, 1))
```
Comment (raptor494) [inline src/main/java/com/aetherteam/aether/data/resources/builders/AetherBiomeBuilders.java:62]: what does this have to do with crafting skyroot buckets?

**Review by raptor494 — APPROVED** [review]
